'use client';
// core styles are required for all packages
import '@mantine/core/styles.css';
import '@mantine/charts/styles.css';
import '@mantine/notifications/styles.css';
import '@mantine/dropzone/styles.css';

// import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { AdminDashboardShell } from '@/components';
import { MantineProvider } from '@mantine/core';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { theme } from '@/theme';
import { Notifications } from '@mantine/notifications';

const inter = Inter({ subsets: ['latin'] });

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

const queryClient = new QueryClient();

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <QueryClientProvider client={queryClient}>
          <MantineProvider theme={theme}>
            <Notifications />
            <AdminDashboardShell>{children}</AdminDashboardShell>
          </MantineProvider>
        </QueryClientProvider>
      </body>
    </html>
  );
}
